services:
  ocrservice.api:
    image: ${DOCKER_REGISTRY-}ocrserviceapi
    build:
      context: .
      dockerfile: OCRService/OCRService.API/Dockerfile
    env_file:
      - OCRService/.env
  # ocrservice.api2:
  #   image: ${DOCKER_REGISTRY-}ocrserviceapi
  #   build:
  #     context: .
  #     dockerfile: OCRService/OCRService.API/Dockerfile
  #   env_file:
  #     - OCRService/.env 

  vqaservice.api:
    image: ${DOCKER_REGISTRY-}vqaserviceapi
    build:
      context: .
      dockerfile: VQAService/VQAService.API/Dockerfile
    env_file:
      - VQAService/.env
  # vqaservice.api2:
  #   image: ${DOCKER_REGISTRY-}vqaserviceapi
  #   build:
  #     context: .
  #     dockerfile: VQAService/VQAService.API/Dockerfile
  #   env_file:
  #     - VQAService/.env

  vqa_database:
    image: mongo:6.0
    env_file:
      - VQAService/.env
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${VQA_DATABASE_MONGO_ROOT_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${VQA_DATABASE_MONGO_ROOT_PASSWORD}"
      MONGO_INITDB_DATABASE:      "${VQA_DATABASE_MONGO_DATABASE}"
    volumes:
      - ./VQAService/.docker/vqa_data:/data/db
      - ./VQAService/.docker/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro

  vqa_database_ui:
    image: mongo-express:1.0.0
    depends_on:
      - vqa_database
    ports:
      - "9812:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER:          "${VQA_DATABASE_MONGO_HOST}"
      ME_CONFIG_MONGODB_PORT:            "${VQA_DATABASE_MONGO_PORT}"
      ME_CONFIG_MONGODB_ADMINUSERNAME:   "${VQA_DATABASE_MONGO_ROOT_USERNAME}"
      ME_CONFIG_MONGODB_ADMINPASSWORD:   "${VQA_DATABASE_MONGO_ROOT_PASSWORD}"
      ME_CONFIG_MONGODB_AUTH_DATABASE:   "${VQA_DATABASE_AUTH_DATABASE}"
      ME_CONFIG_BASICAUTH_USERNAME:      "${VQA_DATABASE_ME_USERNAME}"
      ME_CONFIG_BASICAUTH_PASSWORD:      "${VQA_DATABASE_ME_PASSWORD}"
  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: Gateway/Gateway.API/Dockerfile
    ports:
      - "9990:8080"


  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: IdentityService/IdentityService.API/Dockerfile
    ports:
      - "9989:8080" # Remove after developement

